analyze_cv_task:
  description: >
    Analyze the CV text below and extract:
    - total years of experience
    - experience level (Junior / Intermediate / Senior)
    - tech stack

    CV:
    {cv_text}

  expected_output: >
    A structured analysis of the candidate's experience and skills.
  agent: cv_analyzer


generate_interview_questions:
  description: >
    The user selected the following technology:
    {selected_tech}

    IMPORTANT RULES:
    - ONLY generate interview questions if the selected technology
      exists in the extracted tech stack from the CV analysis.
    - If the selected technology does NOT appear in the CV,
      respond with exactly:
      "Selected technology not found in CV."
    - Comparison should be case-insensitive.

    If the technology is valid:
    - Generate 7–10 interview questions
    - Tailor difficulty based on the candidate’s experience level
    - Keep questions practical and role-appropriate
    - Do not be strict with regards to key words, just check for basic undertanding

  expected_output: >
    Either:
    - "Selected technology not found in CV."
    OR
    - A numbered list of interview questions appropriate for the candidate.
  agent: interviewer
  context:
    - analyze_cv_task

generate_coding_challenge:
  description: >
    The candidate selected the following technology:
    {selected_tech}

    DECIDE FIRST if this technology can be evaluated using a
    programming exercise.

    If the technology is something like:
    cloud, devops, tooling, methodology, or anything
    that does not require writing code,
    respond EXACTLY with:
    "No coding challenge for this technology."
    If the chosen tech stack is a framework, generate a question 
    based on the core language.

    If the technology CAN be tested via programming:

    Create ONE LeetCode-style challenge.

    Difficulty rules:
    - Junior or Intermediate → EASY
    - Senior → MEDIUM

    Provide:
    - Clear problem statement
    - Function signature
    - Constraints
    - Example input/output

  expected_output: >
    Either:
    - "No coding challenge for this technology."
    OR
    - A full coding challenge.
  agent: interviewer
  context:
    - analyze_cv_task
   


