analyze_cv_task:
  description: >
    Analyze the following CV text:

    {cv_text}

    Determine:
    - total years of experience
    - experience level based on:
      - 0–1 years → Junior
      - 2–4 years → Intermediate
      - 5+ years → Senior
    - tech stack, if a framework is given specify the underlying core programming language

    Be concise and accurate.
  expected_output: >
    Years of Experience:
    Experience Level:
    Tech Stack:
  agent: cv_analyzer
